name: Forest Front
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  install-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Lint the code
      - name: Run Linter
        run: npm run lint

      # 6. Build the application
      - name: Build the application
        run: npm run build